In [10]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [15]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [16]:
iris_df['target'] = pd.DataFrame(iris.target)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [ ]:
iris_df['target'] = iris_df['target'].apply(lambda x: iris.target_names[x])

In [27]:
from sklearn.model_selection import train_test_split

In [84]:
X_train, X_test, y_train, y_test = train_test_split(iris_df.drop('target', axis=1).values, iris_df.target.values, test_size=0.1)

In [85]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=20)

In [86]:
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20)

In [87]:
model.score(X_test, y_test)

1.0

In [88]:
import joblib
joblib.dump(model, 'RFC.pkl')

['RFC.pkl']

In [90]:
model.predict([[6.7, 3.0, 5.2, 2.3]])

array(['virginica'], dtype=object)

In [45]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [91]:
reloaded_model = joblib.load('RFC.pkl')

In [104]:
reloaded_model.predict([[6.7, 3.0, 5.5, 2.3]])

array(['virginica'], dtype=object)

In [124]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

In [117]:
log_reg = cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target)
log_reg

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [118]:
dtree = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dtree

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [119]:
rfc = cross_val_score(RandomForestClassifier(n_estimators=20), iris.data, iris.target)
rfc

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [125]:
svc = cross_val_score(SVC(), iris.data, iris.target)
svc

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [126]:
import numpy as np
print(np.average(log_reg), np.average(dtree), np.average(svc),np.average(rfc))

0.9733333333333334 0.9666666666666668 0.9666666666666666 0.9600000000000002
